site:
  title: "Akka Serverless Tools for VSCode Documentation"
  url: https://lightbend.github.io/vscode-akkasls-tools/

content:
  sources:
  - url: https://github.com/lightbend/vscode-akkasls-tools
    branches: [main]
    start_paths: [docs/src]

ui:
  bundle:
    url: https://lightbend.github.io/antora-supplemental-ui-lightbend-theme/default_ui/ui-bundle-1582458925.zip
    snapshot: true
  default_layout: default-dev
  supplemental_files: ./supplemental_ui

runtime:
  fetch: true

asciidoc:

  attributes:
    review: ''
    todo: ''
    page-pagination: ''
    page-toctitle: 'On This Page'
    page-toclevels: 3@


output:
  clean: true
