site:
  title: "Akka Serverless Tools for VSCode Documentation"
  url: https://docs.akkaserverless.dev

content:
  sources:
  - url: ../
    branches: [HEAD]
    start_paths: [docs/src]
    # The following start_path entries allow us to publish WIP, such as the Java and JS and how-to sections
    # to the dev docs but not to prod
    # When one is sufficiently mature to be published to prod, add the path to prod.yml
ui:
  bundle:
    url: https://lightbend.github.io/antora-supplemental-ui-lightbend-theme/default_ui/ui-bundle-1582458925.zip
    snapshot: true
  default_layout: default-dev
  supplemental_files: ./supplemental_ui

runtime:
  fetch: true

asciidoc:

  attributes:
    # the following two attributes cause review and todo notes to display
    review: ''
    todo: ''
    # this attribute causes the next and previous page links to appear at the bottom of the page
    page-pagination: ''
    page-toctitle: 'On This Page'
    page-toclevels: 3@


output:
#   dir: ./build
   clean: true
